package org.example.Tema2.Act2PrioriEstad.example;

public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */


    /*Todo: AQUÍ PUEDES DECLARAR TUS HILOS*/
    Hilos hilo1 = new Hilos("Adrian");
    Hilos hilo2 = new Hilos("Jesus");
    Hilos hilo3 = new Hilos("Eric");
    Hilos hilo4 = new Hilos("Pedro");


    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        starthilo1 = new javax.swing.JButton();
        starthilo2 = new javax.swing.JButton();
        starthilo3 = new javax.swing.JButton();
        starthilo4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sumarprioriHilo1 = new javax.swing.JButton();
        restarprioriHilo1 = new javax.swing.JButton();
        restarprioriHilo2 = new javax.swing.JButton();
        sumarprioriHilo2 = new javax.swing.JButton();
        sumarprioriHilo3 = new javax.swing.JButton();
        restarprioriHilo3 = new javax.swing.JButton();
        sumarprioriHilo4 = new javax.swing.JButton();
        restarprioriHilo4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mediopriorihilo1 = new javax.swing.JButton();
        mediopriorihilo2 = new javax.swing.JButton();
        mediopriorihilo4 = new javax.swing.JButton();
        mediopriorihilo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        starthilo1.setText("Start");
        starthilo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starthilo1MouseClicked(evt);
            }
        });

        starthilo2.setText("Start");
        starthilo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starthilo2MouseClicked(evt);
            }
        });

        starthilo3.setText("Start");
        starthilo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starthilo3MouseClicked(evt);
            }
        });

        starthilo4.setText("Start ");
        starthilo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starthilo4MouseClicked(evt);
            }
        });

        jLabel1.setText("Hilo1");

        jLabel2.setText("Hilo2");

        jLabel3.setText("Hilo3");

        jLabel4.setText("Hilo4");

        sumarprioriHilo1.setText("alta");
        sumarprioriHilo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarprioriHilo1MouseClicked(evt);
            }
        });

        restarprioriHilo1.setText("baja");
        restarprioriHilo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarprioriHilo1MouseClicked(evt);
            }
        });

        restarprioriHilo2.setText("baja");
        restarprioriHilo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarprioriHilo2MouseClicked(evt);
            }
        });

        sumarprioriHilo2.setText("alta");
        sumarprioriHilo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarprioriHilo2MouseClicked(evt);
            }
        });

        sumarprioriHilo3.setText("alta");
        sumarprioriHilo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarprioriHilo3MouseClicked(evt);
            }
        });

        restarprioriHilo3.setText("baja");
        restarprioriHilo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarprioriHilo3MouseClicked(evt);
            }
        });

        sumarprioriHilo4.setText("alta");
        sumarprioriHilo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarprioriHilo4MouseClicked(evt);
            }
        });

        restarprioriHilo4.setText("baja");
        restarprioriHilo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarprioriHilo4MouseClicked(evt);
            }
        });

        jLabel5.setText("Prioridad");

        jLabel6.setText("Prioridad");

        jLabel7.setText("Prioridad");

        jLabel8.setText("Prioridad");

        mediopriorihilo1.setText("normal");
        mediopriorihilo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediopriorihilo1MouseClicked(evt);
            }
        });

        mediopriorihilo2.setText("normal");
        mediopriorihilo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediopriorihilo2MouseClicked(evt);
            }
        });

        mediopriorihilo4.setText("normal");
        mediopriorihilo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediopriorihilo4MouseClicked(evt);
            }
        });

        mediopriorihilo3.setText("normal");
        mediopriorihilo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediopriorihilo3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(124, 124, 124)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(restarprioriHilo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(mediopriorihilo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                .addComponent(starthilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(93, 93, 93)))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(sumarprioriHilo1)
                                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(22, 22, 22)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(starthilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(starthilo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sumarprioriHilo4)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(mediopriorihilo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(sumarprioriHilo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(restarprioriHilo4)
                                                        .addComponent(mediopriorihilo4)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(starthilo3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sumarprioriHilo3)
                                                        .addComponent(restarprioriHilo3)
                                                        .addComponent(mediopriorihilo3)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(206, 206, 206)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(restarprioriHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel5))
                                                .addGap(16, 16, 16)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sumarprioriHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(starthilo1)
                                        .addComponent(starthilo2)
                                        .addComponent(sumarprioriHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mediopriorihilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mediopriorihilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(restarprioriHilo1)
                                        .addComponent(restarprioriHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(starthilo3)
                                                        .addComponent(starthilo4)
                                                        .addComponent(sumarprioriHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sumarprioriHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(mediopriorihilo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mediopriorihilo4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(restarprioriHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(restarprioriHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void starthilo1MouseClicked(java.awt.event.MouseEvent evt) {
        try{
            if(!hilo1.isAlive()){//si no esta ocupado
                hilo1 = new Hilos("Adrian");
                hilo1.start();
            }else {//le da al boton y el hilo no esta ocupado
                System.out.println("Hilo ocupado, creando nuevo hilo");
                Hilos hiloNuevAdri = new Hilos("nuevoAdri");
                hiloNuevAdri.start();
            }
        }catch (IllegalThreadStateException es) {
            System.out.println(hilo1.getName()+ ": ocupado");
        }
    }

    private void starthilo2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        try{
            if(!hilo2.isAlive()){//si no esta ocupado
                hilo2 = new Hilos("Jesus");
                hilo2.start();
            }else {//le da al boton y el hilo no esta ocupado
                System.out.println("Hilo ocupado, creando nuevo hilo");
                Hilos hiloNuevJesus = new Hilos("nuevoJesus");
                hiloNuevJesus.start();
            }
        }catch (IllegalThreadStateException es) {
            System.out.println(hilo2.getName()+ ": ocupado");
        }

    }

    private void starthilo3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        try{
            if(!hilo3.isAlive()){//si no esta ocupado
                hilo3 = new Hilos("Eric");
                hilo3.start();
            }else {//le da al boton y el hilo no esta ocupado
                System.out.println("Hilo ocupado, creando nuevo hilo");
                Hilos hiloNuevEri = new Hilos("nuevoEri");
                hiloNuevEri.start();
            }
        }catch (IllegalThreadStateException es) {
            System.out.println(hilo3.getName()+ ": ocupado");
        }
    }

    private void starthilo4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        try{
            if(!hilo4.isAlive()){//si no esta ocupado
                hilo4 = new Hilos("Pedro");
                hilo4.start();
            }else {//le da al boton y el hilo no esta ocupado
                System.out.println("Hilo ocupado, creando nuevo hilo");
                Hilos hiloNuevPedro = new Hilos("nuevoPedro");
                hiloNuevPedro.start();
            }
        }catch (IllegalThreadStateException es) {
            System.out.println(hilo4.getName()+ ": ocupado");
        }
    }

    private void sumarprioriHilo1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo1.isAlive()){
            hilo1.setPriority(Thread.MAX_PRIORITY);
            System.out.println(hilo1.getName() + " prioridad: Alta");
        }else{
            System.out.println(hilo1.getName()+": hilo dormido");
        }
    }

    private void restarprioriHilo1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo1.isAlive()){
            hilo1.setPriority(Thread.MIN_PRIORITY);
            System.out.println(hilo1.getName() + " prioridad: baja");
        }else{
            System.out.println(hilo1.getName()+": hilo dormido");
        }
    }

    private void mediopriorihilo1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo1.isAlive()){
            hilo1.setPriority(Thread.NORM_PRIORITY);
            System.out.println(hilo1.getName() + " prioridad: media");
        }else{
            System.out.println(hilo1.getName()+": hilo dormido");
        }
    }

    private void sumarprioriHilo2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo2.isAlive()){
            hilo2.setPriority(Thread.MAX_PRIORITY);
            System.out.println(hilo2.getName() + " prioridad: Alta");
        }else{
            System.out.println(hilo2.getName()+": hilo dormido");
        }
    }

    private void mediopriorihilo2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo2.isAlive()){
            hilo1.setPriority(Thread.NORM_PRIORITY);
            System.out.println(hilo2.getName() + " prioridad: media");
        }else{
            System.out.println(hilo2.getName()+": hilo dormido");
        }
    }

    private void restarprioriHilo2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo2.isAlive()){
            hilo2.setPriority(Thread.MIN_PRIORITY);
            System.out.println(hilo2.getName() + " prioridad: baja");
        }else{
            System.out.println(hilo2.getName()+": hilo dormido");
        }
    }

    private void sumarprioriHilo3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo3.isAlive()){
            hilo3.setPriority(Thread.MAX_PRIORITY);
            System.out.println(hilo3.getName() + " prioridad: Alta");
        }else{
            System.out.println(hilo3.getName()+": hilo dormido");
        }
    }

    private void mediopriorihilo3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo3.isAlive()){
            hilo3.setPriority(Thread.NORM_PRIORITY);
            System.out.println(hilo3.getName() + " prioridad: media");
        }else{
            System.out.println(hilo3.getName()+": hilo dormido");
        }
    }

    private void restarprioriHilo3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo3.isAlive()){
            hilo3.setPriority(Thread.MIN_PRIORITY);
            System.out.println(hilo3.getName() + " prioridad: baja");
        }else{
            System.out.println(hilo3.getName()+": hilo dormido");
        }
    }

    private void sumarprioriHilo4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo4.isAlive()){
            hilo4.setPriority(Thread.MAX_PRIORITY);
            System.out.println(hilo4.getName() + " prioridad: Alta");
        }else{
            System.out.println(hilo4.getName()+": hilo dormido");
        }
    }

    private void mediopriorihilo4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo4.isAlive()){
            hilo4.setPriority(Thread.NORM_PRIORITY);
            System.out.println(hilo4.getName() + " prioridad: media");
        }else{
            System.out.println(hilo4.getName()+": hilo dormido");
        }
    }

    private void restarprioriHilo4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO TU CÓDIGO AQUÍ
        if(hilo4.isAlive()){
            hilo4.setPriority(Thread.MIN_PRIORITY);
            System.out.println(hilo4.getName() + " prioridad: baja");
        }else{
            System.out.println(hilo4.getName()+": hilo dormido");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton mediopriorihilo1;
    private javax.swing.JButton mediopriorihilo2;
    private javax.swing.JButton mediopriorihilo3;
    private javax.swing.JButton mediopriorihilo4;
    private javax.swing.JButton restarprioriHilo1;
    private javax.swing.JButton restarprioriHilo2;
    private javax.swing.JButton restarprioriHilo3;
    private javax.swing.JButton restarprioriHilo4;
    private javax.swing.JButton starthilo1;
    private javax.swing.JButton starthilo2;
    private javax.swing.JButton starthilo3;
    private javax.swing.JButton starthilo4;
    private javax.swing.JButton sumarprioriHilo1;
    private javax.swing.JButton sumarprioriHilo2;
    private javax.swing.JButton sumarprioriHilo3;
    private javax.swing.JButton sumarprioriHilo4;
    // End of variables declaration
}

